import java.util.List;
import java.util.function.Predicate;

import static java.util.stream.Collectors.toList;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zhxia' at '1/4/17 11:56 PM' with Gradle 3.1
 *
 * @author zhxia, @date 1/4/17 11:56 PM
 */
public class Person {
    private int age;
    private String name;
    private String gender;

    public Person(int age, String name, String gender) {
        this.age = age;
        this.name = name;
        this.gender = gender;
    }

    public int getAge() {
        return age;
    }

    public String getGender() {
        return gender;
    }

    public static List<Person> filterAdultMan(List<Person> persons) {
        return persons.stream().filter(isAdultMan()).collect(toList());
    }

    private static Predicate<Person> isAdultMan() {
        return p -> p.getAge() > 18 && p.getGender().equalsIgnoreCase("M");
    }
}
